In [5]:
import numpy as np

def rotz(a):
    c, s = np.cos(a), np.sin(a)
    return np.array([
        [c,-s,0,0],
        [s, c,0,0],
        [0, 0,1,0],
        [0, 0,0,1]
    ])

def rotx(a):
    c, s = np.cos(a), np.sin(a)
    return np.array([
        [1,0,0,0],
        [0,c,-s,0],
        [0,s,c,0],
        [0,0,0,1]
    ])

def roty(a):
    c, s = np.cos(a), np.sin(a)
    return np.array([
        [c,0,s,0],
        [0,1,0,0],
        [-s,0,c,0],
        [0,0,0,1]
    ])

def transl(x,y,z):
    T = np.eye(4)
    T[:3,3] = [x,y,z]
    return T

def rpy(r,p,y):
    return rotz(y) @ roty(p) @ rotx(r)

In [6]:
def fk(q):

    q1,q2,q3,q4,q5 = q

    T_world_base = transl(0,0,0) @ rpy(0,0,3.14159)

    T_base_shoulder = transl(0,-0.0452,0.0165)
    T_shoulder_upper = transl(0,-0.0306,0.1025) @ rpy(0,-1.57079,0)
    T_upper_lower = transl(0.11257,-0.028,0)
    T_lower_wrist = transl(0.0052,-0.1349,0) @ rpy(0,0,1.57079)
    T_wrist_gripper = transl(-0.0601,0,0) @ rpy(0,-1.57079,0)
    T_gripper_center = transl(0,0,0.075)

    T = (
        T_world_base
        @ T_base_shoulder @ rotz(q1)
        @ T_shoulder_upper @ rotz(q2)
        @ T_upper_lower @ rotz(q3)
        @ T_lower_wrist @ rotz(q4)
        @ T_wrist_gripper @ rotz(q5)
        @ T_gripper_center
    )

    return T


In [8]:
q = [0,0,0,0,0]

T = fk(q)

p = T[:3,3]

print("Transform:")
print(T)

print("End effector positie:")
print(p)

Transform:
[[ 1.00000000e+00  6.32677811e-06  8.98042472e-06  7.21320255e-07]
 [-8.98038469e-06 -6.32681169e-06  1.00000000e+00  3.73800000e-01]
 [ 6.32683492e-06 -1.00000000e+00 -6.32675487e-06  2.36769145e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
End effector positie:
[7.21320255e-07 3.73800000e-01 2.36769145e-01]


In [9]:
p = fk(q)[:3,3]

In [10]:
import numpy as np

q = np.random.uniform(-np.pi,np.pi,5)

T = fk(q)

print("q =", q)
print("positie =", T[:3,3])

q = [ 0.79514118 -2.22148517 -0.11593579 -0.78140431  0.74521005]
positie = [ 0.0868855  -0.04000668 -0.07531083]


In [11]:
def ee_position(q):
    return fk(q)[:3,3]

In [12]:
fk([0,0,0,0,0])

array([[ 1.00000000e+00,  6.32677811e-06,  8.98042472e-06,
         7.21320255e-07],
       [-8.98038469e-06, -6.32681169e-06,  1.00000000e+00,
         3.73800000e-01],
       [ 6.32683492e-06, -1.00000000e+00, -6.32675487e-06,
         2.36769145e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [13]:
fk([0.5,0,0,0,0])

array([[ 8.77586867e-01,  8.58550524e-06, -4.79417658e-01,
        -1.57538584e-01],
       [ 4.79417658e-01, -2.51908061e-06,  8.77586867e-01,
         3.33573918e-01],
       [ 6.32683492e-06, -1.00000000e+00, -6.32675487e-06,
         2.36769145e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [14]:
fk([0,0,0.5,0,0])

array([[ 1.00000000e+00,  6.82448805e-06,  5.62235515e-06,
        -1.87946934e-07],
       [-8.20589386e-06,  4.79419986e-01,  8.77585595e-01,
         3.38254689e-01],
       [ 3.29360297e-06, -8.77585595e-01,  4.79419986e-01,
         3.65577575e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])